/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Admin.AdminMain;
import Driver.Driver;
import Employee.EmployeeMain;
import SQLAccess.DataAccess;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author VuManh
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setTitle("Gym Information");
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblWarning = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 20));
        getContentPane().add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 180, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, 20));
        getContentPane().add(tfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 180, -1));

        jButton1.setText("About");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 90, 40));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/login.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 100, -1));

        lblWarning.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 180, 20));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/carrrrrrrrrrrrrr.gif"))); // NOI18N
        getContentPane().add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int info;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            String ID = tfID.getText();
            String pass = new String(tfPass.getPassword());

            String command = "select * from [Account]";
            ResultSet rs = DataAccess.getPreparedStatement(command).executeQuery();

            while(rs.next()){
                if(ID.equals(rs.getString("id")) && pass.equals(rs.getString("[password]")) && rs.getInt("[status]")==1)
                {
                    lblWarning.setText("Correct input!");
                    info = rs.getRow();
                    String userType = rs.getString("userType");
                    switch(userType){
                        case "admin":
                        JOptionPane.showMessageDialog(this, "Admin");
                        this.setVisible(false);
                        AdminMain ad = new AdminMain();
                        ad.userRow = info;
                        ad.setVisible(true);
                        break;

                        case "staff":
                        JOptionPane.showMessageDialog(this, "Staff");
                        this.setVisible(false);
                        EmployeeMain em = new EmployeeMain();
                        em.userRow = info;
                        em.setVisible(true);
                        break;
                    }
                }else{
                    lblWarning.setText("Incorrect input!");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JTextField tfID;
    private javax.swing.JPasswordField tfPass;
    // End of variables declaration//GEN-END:variables
}
